import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { createApp } from '../server/app.ts';
import type { ModelRequest, ProviderAdapter } from '../server/providers.ts';
import { providerSchema, type ModelResponse, type Project } from '../shared/contracts.ts';
import { hash, Workspace, type Checkpoint } from '../server/workspace.ts';
import { cleanup } from './helpers.ts';
const respond=(text:string,tool?:{name:string;arguments:Record<string,unknown>}):ModelResponse=>({text,toolCalls:tool?[{id:crypto.randomUUID(),...tool}]:[],usage:{input:100,output:20,cached:0,cost:0.0002,providerId:'p',modelId:'fixture'},finishReason:tool?'tool_calls':'stop'});
async function setup(adapter:ProviderAdapter){const root=await fs.mkdtemp(path.join(os.tmpdir(),'agentscope-test-')),projectRoot=path.join(root,'project');await fs.mkdir(projectRoot);const app=await createApp({root:process.cwd(),dataDirectory:path.join(root,'data'),port:4398,adapter});const project:Project={id:'p',root:projectRoot,name:'Fixture repo',createdAt:''};app.store.put('projects','p',project);app.store.put('providers','p',providerSchema.parse({id:'p',name:'Fixture provider (test only)',kind:'compatible',baseUrl:'http://localhost:9999/v1',models:[{id:'fixture',name:'Test fixture',inputPrice:1,outputPrice:5}]}));await app.vault.unlock('fixture-passphrase');return {...app,root,project,async dispose(){await app.close();await cleanup(root);}};}
test('agent loop finds a bug, edits a real file, runs real tests, observes output and creates a recoverable checkpoint',async()=>{
  const original='export function add(a, b) { return a - b; }\n';let step=0;const seen:Omit<ModelRequest,'signal'>[]=[];
  const adapter:ProviderAdapter={async complete(request){seen.push(structuredClone({...request,signal:undefined}));step++;if(step===1)return respond('',{name:'repo_search',arguments:{query:'add'}});if(step===2)return respond('',{name:'discover_tools',arguments:{category:'files'}});if(step===3)return respond('',{name:'file_read',arguments:{path:'math.mjs'}});if(step===4){assert.ok(request.messages.some(m=>m.role==='tool'&&m.content.includes('return a - b')));return respond('',{name:'file_replace',arguments:{path:'math.mjs',search:'a - b',replacement:'a + b',expectedHash:hash(original)}});}if(step===5)return respond('',{name:'discover_tools',arguments:{category:'shell'}});if(step===6)return respond('',{name:'shell_run',arguments:{command:'node --test math.test.mjs'}});assert.ok(request.messages.at(-1)?.content.includes('"exitCode":0'));return respond('Fixed addition. The regression test passed.');}};
  const f=await setup(adapter);try{await fs.writeFile(path.join(f.project.root,'math.mjs'),original);await fs.writeFile(path.join(f.project.root,'math.test.mjs'),'import assert from "node:assert/strict"; import { test } from "node:test"; import { add } from "./math.mjs"; test("adds positive numbers", () => assert.equal(add(4, 3), 7));');for(const capability of ['write','shell'] as const)f.permissions.add({id:capability,capability,pattern:'*',decision:'allow',scope:'project',projectId:'p'});const task=f.runtime.create({projectId:'p',providerId:'p',modelId:'fixture',mode:'code'});const result=await f.runtime.run(task.id,'Find and fix the addition bug.');assert.match(result,/regression test passed/);assert.equal(f.runtime.task(task.id).status,'done');assert.equal(await fs.readFile(path.join(f.project.root,'math.mjs'),'utf8'),'export function add(a, b) { return a + b; }\n');assert.equal(f.store.all('usage').length,7);assert.ok(seen[0]!.tools.length<seen[3]!.tools.length);const checkpoint=f.store.get<Checkpoint>('checkpoints',`${task.id}:math.mjs`)!;await new Workspace(f.project.root,f.store,'p').restore(checkpoint);assert.equal(await fs.readFile(path.join(f.project.root,'math.mjs'),'utf8'),original);}finally{await f.dispose();}
});
test('runtime stops a pending approval without writing or making another model call',async()=>{let calls=0;const f=await setup({async complete(){calls++;return respond('',{name:'file_write',arguments:{path:'denied.txt',content:'must not happen',expectedHash:null}});}});try{const task=f.runtime.create({projectId:'p',providerId:'p',modelId:'fixture',mode:'code'});const running=f.runtime.run(task.id,'Use files tools to create a file.');for(let i=0;i<100&&!f.permissions.list().length;i++)await new Promise(r=>setTimeout(r,10));assert.equal(f.permissions.list().length,1);f.runtime.stop(task.id);await running;assert.equal(calls,1);assert.equal(f.runtime.task(task.id).status,'stopped');assert.equal(f.permissions.list().length,0);await assert.rejects(fs.stat(path.join(f.project.root,'denied.txt')),/ENOENT/);}finally{await f.dispose();}});
test('workflow feeds verified output into the next step and attributes child usage to the root',async()=>{const inputs:string[]=[];const f=await setup({async complete(req){inputs.push(req.messages.at(-1)!.content);return respond(inputs.length===1?'Architecture: math.mjs exports add.':'Review complete.');}});try{const task=f.runtime.create({projectId:'p',providerId:'p',modelId:'fixture',mode:'workflow'});await f.runtime.run(task.id,'Explain the unfamiliar repository.',{workflow:{id:'w',name:'Review',description:'',steps:[{name:'Explore',mode:'ask',prompt:'Explain the repo.'},{name:'Review',mode:'ask',prompt:'Review the explanation.'}]}});assert.equal(inputs.length,2);assert.match(inputs[1]!,/Architecture: math.mjs/);assert.equal(f.runtime.task(task.id).status,'done');assert.ok(f.store.all<{rootTaskId:string}>('usage').every(u=>u.rootTaskId===task.id));}finally{await f.dispose();}});
test('configured budget blocks provider calls before they spend money',async()=>{let calls=0;const f=await setup({async complete(){calls++;return respond('Should never be requested.');}});try{f.store.put('settings','app',{...f.runtime.settings(),taskLimit:0.000001});const task=f.runtime.create({projectId:'p',providerId:'p',modelId:'fixture',mode:'ask'});await f.runtime.run(task.id,'Explain the repository.');assert.equal(calls,0);assert.equal(f.runtime.task(task.id).status,'error');assert.match(f.runtime.task(task.id).error??'',/spending limit/);}finally{await f.dispose();}});
test('local API enforces session, host, origin and write-header boundaries; saved provider keys never appear in state',async()=>{const f=await setup({async complete(){return respond('Hello');}});const server=f.app.listen(4398,'127.0.0.1');try{await new Promise<void>(resolve=>server.once('listening',resolve));const base='http://127.0.0.1:4398';assert.equal((await fetch(base+'/api/state')).status,401);const session=await fetch(base+'/api/session');const cookie=session.headers.get('set-cookie')!.split(';')[0]!;assert.equal((await fetch(base+'/api/state',{headers:{cookie,origin:'https://untrusted.example'}})).status,403);assert.equal((await fetch(base+'/api/settings',{method:'POST',headers:{cookie,'content-type':'application/json'},body:'{}'})).status,403);f.vault.set('p',{apiKey:'secret-do-not-leak',headers:{Authorization:'very-private'}});const response=await fetch(base+'/api/state',{headers:{cookie}});const body=await response.text();assert.equal(response.status,200);assert.ok(body.includes('"hasKey":true'));assert.ok(!body.includes('secret-do-not-leak'));assert.ok(!body.includes('very-private'));}finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));await f.dispose();}});
