import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fixture } from './helpers.ts';
import { Vault } from '../server/vault.ts';
import { Workspace, hash, type Checkpoint } from '../server/workspace.ts';
import { Permissions } from '../server/permissions.ts';
import { safeUrl } from '../server/browser.ts';
import { validateEndpoint } from '../server/providers.ts';

test('vault encrypts secrets, rejects bad passphrases and redacts saved keys and headers',async()=>{const f=await fixture();try{const vault=new Vault(f.store);await vault.unlock('test-passphrase-long');vault.set('provider',{apiKey:'secret-key-never-public',headers:{'X-Secret':'header-secret-never-public'}});const stored=JSON.stringify(f.store.get('vault','secrets'));assert.ok(!stored.includes('secret-key'));assert.ok(!stored.includes('header-secret'));assert.equal(vault.redact('secret-key-never-public header-secret-never-public'),'[REDACTED] [REDACTED]');vault.lock();assert.throws(()=>vault.get('provider'),/Unlock/);await assert.rejects(vault.unlock('incorrect-passphrase'),/Incorrect/);await vault.unlock('test-passphrase-long');assert.equal(vault.get('provider').apiKey,'secret-key-never-public');}finally{await f.close();}});
test('workspace rejects traversal, absolute paths, credentials and junction escapes',async()=>{const f=await fixture();try{const w=new Workspace(f.project,f.store,'p');await assert.rejects(w.resolve('../escape.txt'),/outside/);await assert.rejects(w.resolve(path.join(f.root,'escape.txt')),/relative/);await assert.rejects(w.resolve('.env.local'),/Protected/);await fs.mkdir(path.join(f.root,'outside'));await fs.symlink(path.join(f.root,'outside'),path.join(f.project,'linked'),process.platform==='win32'?'junction':'dir');await assert.rejects(w.resolve('linked/file.txt'),/Symbolic/);}finally{await f.close();}});
test('edits reject stale hashes, preserve original snapshots, and restore safely',async()=>{const f=await fixture();try{const w=new Workspace(f.project,f.store,'p');await fs.writeFile(path.join(f.project,'a.ts'),'const a = 1;\n');await w.write('a.ts','const a = 2;\n',hash('const a = 1;\n'),'t');await assert.rejects(w.write('a.ts','wrong',hash('const a = 1;\n'),'t'),/changed/);await w.write('a.ts','const a = 3;\n',hash('const a = 2;\n'),'t');const cp=f.store.get<Checkpoint>('checkpoints','t:a.ts')!;assert.equal(cp.before,'const a = 1;\n');await fs.writeFile(path.join(f.project,'a.ts'),'user edit');await assert.rejects(w.restore(cp),/later changes/);assert.equal((await w.read('a.ts')).content,'user edit');await fs.writeFile(path.join(f.project,'a.ts'),'const a = 3;\n');await w.restore(cp);assert.equal((await w.read('a.ts')).content,'const a = 1;\n');}finally{await f.close();}});
test('patch, create and deletion checkpoints restore exact content',async()=>{const f=await fixture();try{const w=new Workspace(f.project,f.store,'p');await w.write('new.txt','one\ntwo\n',null,'create');const cp=f.store.get<Checkpoint>('checkpoints','create:new.txt')!;await w.patch('new.txt','@@ -1,2 +1,2 @@\n one\n-two\n+three\n',hash('one\ntwo\n'),'patch');assert.equal((await w.read('new.txt')).content,'one\nthree\n');await w.restore(f.store.get<Checkpoint>('checkpoints','patch:new.txt')!);await w.remove('new.txt',hash('one\ntwo\n'),'delete');await w.restore(f.store.get<Checkpoint>('checkpoints','delete:new.txt')!);await w.restore(cp);await assert.rejects(w.read('new.txt'),/ENOENT/);}finally{await f.close();}});
test('deny wins over allow, project rules are scoped, Ask cannot mutate',async()=>{const f=await fixture();try{const p=new Permissions(f.store);p.add({id:'allow',capability:'shell',pattern:'npm *',decision:'allow',scope:'project',projectId:'p'});p.add({id:'deny',capability:'shell',pattern:'npm publish*',decision:'deny',scope:'global'});assert.equal(p.decision('shell','npm test','p','code'),'allow');assert.equal(p.decision('shell','npm test','other','code'),'ask');assert.equal(p.decision('shell','npm publish','p','code'),'deny');assert.equal(p.decision('shell','npm test','p','ask'),'deny');assert.equal(p.decision('write','src/a.ts','p','ask'),'deny');}finally{await f.close();}});
test('approval resolves once and cancelling a waiting task clears its request',async()=>{const f=await fixture();try{const p=new Permissions(f.store),controller=new AbortController();const request={taskId:'t',projectId:'p',capability:'write' as const,target:'src/a.ts',description:'Edit a.ts'};const waiting=p.require(request,'code',controller.signal);assert.equal(p.list().length,1);p.respond(p.list()[0]!.id,'once');await waiting;assert.equal(p.decision('write','src/a.ts','p','code'),'ask');const cancelled=p.require(request,'code',controller.signal);controller.abort();await assert.rejects(cancelled);assert.equal(p.list().length,0);}finally{await f.close();}});
test('provider endpoints and web tools block unsafe schemes and embedded credentials',()=>{assert.throws(()=>validateEndpoint('http://api.example.com/v1'),/HTTPS/);assert.throws(()=>validateEndpoint('https://secret@example.com/v1'),/credentials/);assert.throws(()=>safeUrl('file:///etc/passwd'),/HTTP/);assert.throws(()=>safeUrl('http://169.254.169.254/latest/meta-data'),/Metadata/);assert.throws(()=>safeUrl('http://localhost:4317/api/state'),/control service/);assert.equal(validateEndpoint('http://localhost:11434/v1/'),'http://localhost:11434/v1');});
