import { test, expect } from '@playwright/test';
import type { Server } from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import express from 'express';
import { createApp } from '../server/app.ts';
import { cleanup } from './helpers.ts';
import { hash } from '../server/workspace.ts';
import type { ModelResponse } from '../shared/contracts.ts';
let application:Awaited<ReturnType<typeof createApp>>,server:Server,root:string,project:string;
const original='export function add(a, b) { return a - b; }\n';
const reply=(name?:string,args:Record<string,unknown>={}):ModelResponse=>({text:name?'':'Fixed addition and verified it with the regression test. All tests passed.',toolCalls:name?[{id:crypto.randomUUID(),name,arguments:args}]:[],usage:{input:100,output:20,cached:0,cost:0.0002,providerId:'test',modelId:'scripted-fixture'},finishReason:name?'tool_calls':'stop'});
test.beforeAll(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'agentscope-test-'));project=path.join(root,'arithmetic-fixture');await fs.mkdir(project);await fs.writeFile(path.join(project,'math.mjs'),original);await fs.writeFile(path.join(project,'math.test.mjs'),'import { test } from "node:test"; import assert from "node:assert/strict"; import { add } from "./math.mjs"; test("addition",()=>assert.equal(add(2,3),5));');application=await createApp({root:process.cwd(),dataDirectory:path.join(root,'data'),port:4397,adapter:{async complete(req){const last=req.messages.at(-1);if(last?.role==='user')return reply('file_read',{path:'math.mjs'});if(last?.name==='file_read')return reply('discover_tools',{category:'files'});if(last?.name==='discover_tools'&&last.content.includes('file_replace'))return reply('file_replace',{path:'math.mjs',search:'a - b',replacement:'a + b',expectedHash:hash(original)});if(last?.name==='file_replace')return reply('discover_tools',{category:'shell'});if(last?.name==='discover_tools')return reply('shell_run',{command:'node --test math.test.mjs'});if(!last?.content.includes('"exitCode":0'))throw new Error('Regression test did not pass.');return reply();}}});application.app.use(express.static(path.resolve('dist')));application.app.get('/{*path}',(_req,res)=>res.sendFile(path.resolve('dist/index.html')));server=application.app.listen(4397,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));});
test.afterAll(async()=>{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));await application.close();await cleanup(root);});
test('first run → encrypted provider → project → approved edit → actual test → checkpoint restore',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:4397');await expect(page.getByRole('heading',{name:'Your model. A better agent around it.'})).toBeVisible();
  await page.getByRole('button',{name:'Connect a model'}).click();await page.getByLabel(/^Vault passphrase/).fill('browser-fixture-passphrase');await page.getByLabel('Confirm passphrase').fill('browser-fixture-passphrase');await page.getByRole('button',{name:'Create encrypted vault'}).click();await page.getByRole('button',{name:'Custom provider',exact:true}).click();await page.getByLabel('Display name',{exact:true}).first().fill('Deterministic test provider');await page.getByLabel(/^API key/).fill('TEST_ONLY_NEVER_A_REAL_KEY');await page.getByLabel(/^Model ID/).fill('scripted-fixture');await page.getByRole('button',{name:'Save provider',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:/2 Open your project/}).click();await page.getByLabel('Absolute folder path').fill(project);await page.getByRole('button',{name:'Open & index project'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByLabel('Task prompt').fill('Find and fix the addition bug.');await page.getByRole('button',{name:'Send task'}).click();await expect(page.getByText('Permission needed',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Allow once',exact:true}).click();await expect(page.getByText('Permission needed',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Allow once',exact:true}).click();await expect(page.getByText('Fixed addition and verified it with the regression test. All tests passed.',{exact:true})).toBeVisible();await expect.poll(()=>fs.readFile(path.join(project,'math.mjs'),'utf8')).toBe('export function add(a, b) { return a + b; }\n');
  await page.getByRole('button',{name:'Changes',exact:true}).click();await page.locator('.diff-item summary').click();await page.getByRole('button',{name:'Restore this file',exact:true}).click();await expect.poll(()=>fs.readFile(path.join(project,'math.mjs'),'utf8')).toBe(original);expect(errors).toEqual([]);
});
test('skill editor, memory, workflow, settings and command palette remain functional',async({page})=>{
  await page.goto('http://127.0.0.1:4397');await page.getByRole('button',{name:/^Skills/}).click();await expect(page.getByRole('heading',{name:'A skill for the task.'})).toBeVisible();await page.getByLabel('Search skills').fill('minecraft');await expect(page.getByRole('button',{name:'minecraft plugins',exact:true})).toBeVisible();await page.getByRole('button',{name:'Create skill',exact:true}).click();await page.getByLabel('Skill instructions').fill('---\nname: ui-regression\ndescription: Verify the editor accepts continued typing.\n---\n\nCheck the user flow.');await page.getByRole('button',{name:'Save skill',exact:true}).click();await page.getByLabel('Search skills').fill('ui-regression');await expect(page.getByRole('button',{name:'ui regression',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Memory',exact:true}).click();await page.getByRole('button',{name:'Add memory',exact:true}).click();await page.getByLabel('Title',{exact:true}).pressSequentially('Use focused tests');await page.getByLabel('Knowledge').fill('Run only the relevant regression tests before the full suite.');await page.getByRole('button',{name:'Save memory',exact:true}).click();await expect(page.getByRole('heading',{name:'Use focused tests',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Workflows',exact:true}).click();await expect(page.getByRole('heading',{name:'Ship a change',exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit Ship a change'}).click();await page.getByLabel('Name',{exact:true}).fill('Ship a careful change');await page.getByRole('button',{name:'Save workflow',exact:true}).click();await expect(page.getByRole('heading',{name:'Ship a careful change',exact:true})).toBeVisible();
  await page.keyboard.press('Control+k');await page.getByLabel('Search commands').fill('view usage');await page.getByRole('button',{name:/View usage/}).click();await expect(page.getByRole('heading',{name:'Every token, accounted for.'})).toBeVisible();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Shortcuts',exact:true}).click();await expect(page.getByLabel('palette',{exact:true})).toHaveValue('mod+k');
});
test('mobile navigation, dialog focus and keyboard dismissal work without overflow',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4397');await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('button',{name:/^Skills/}).click();await expect(page.getByRole('heading',{name:'A skill for the task.'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('button',{name:'Create skill',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);});
