#!/usr/bin/env bash
# Install a git pre-commit hook that blocks commits containing likely secrets.
#
# Usage:
#   ./install_precommit.sh [REPO_DIR]
#
# - REPO_DIR defaults to the current directory.
# - The hook runs scan_secrets.py over the staged files and aborts on findings.
# - Bypass intentionally with: git commit --no-verify  (use sparingly)
set -euo pipefail

REPO_DIR="${1:-$(pwd)}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! -d "$REPO_DIR/.git" ]; then
  echo "error: $REPO_DIR is not a git repository (no .git directory)" >&2
  exit 1
fi

HOOK_DIR="$REPO_DIR/.git/hooks"
HOOK_PATH="$HOOK_DIR/pre-commit"
mkdir -p "$HOOK_DIR"

if [ -f "$HOOK_PATH" ] && ! grep -q "scan_secrets.py" "$HOOK_PATH" 2>/dev/null; then
  echo "warning: existing pre-commit hook found; backing up to pre-commit.bak" >&2
  cp "$HOOK_PATH" "$HOOK_PATH.bak"
fi

cat > "$HOOK_PATH" <<HOOK
#!/usr/bin/env bash
# Auto-generated by install_precommit.sh — blocks commits containing secrets.
set -euo pipefail

SCANNER="${SCRIPT_DIR}/scan_secrets.py"
if [ ! -f "\$SCANNER" ]; then
  echo "secret scanner not found at \$SCANNER; skipping" >&2
  exit 0
fi

# Collect staged, added/modified text files.
mapfile -t FILES < <(git diff --cached --name-only --diff-filter=ACM)
if [ "\${#FILES[@]}" -eq 0 ]; then
  exit 0
fi

if ! python3 "\$SCANNER" "\${FILES[@]}" --quiet; then
  echo "" >&2
  echo "Commit blocked: potential secret detected in staged changes." >&2
  echo "Rotate the secret if it is real, remove it from the diff, then recommit." >&2
  echo "To bypass intentionally: git commit --no-verify" >&2
  exit 1
fi
exit 0
HOOK

chmod +x "$HOOK_PATH"
echo "Installed pre-commit secret scanner at $HOOK_PATH"
echo "Test it with: git add . && git commit -m test"
