import { useEffect, useRef, useState, type ReactNode } from 'react';
import { X, Loader2, AlertCircle, Check, ArrowUpRight, Focus } from 'lucide-react';
export function Logo({small=false}:{small?:boolean}){return <span className={'logo '+(small?'small':'')}><Focus size={small?18:23} strokeWidth={1.8}/></span>;}
export function Button({children,onClick,disabled=false,kind='secondary',type='button',className='',title}:{children:ReactNode;onClick?:()=>void;disabled?:boolean;kind?:'primary'|'secondary'|'danger'|'ghost';type?:'button'|'submit';className?:string;title?:string}){return <button type={type} className={`button ${kind} ${className}`} onClick={onClick} disabled={disabled} title={title}>{children}</button>;}
export function ErrorBox({message}:{message:string}){return message?<div className="error-box" role="alert"><AlertCircle size={16}/><span>{message}</span></div>:null;}
export function Empty({icon,heading,children,action}:{icon?:ReactNode;heading:string;children?:ReactNode;action?:ReactNode}){return <div className="empty"><div className="empty-icon">{icon??<Focus size={25}/>}</div><h3>{heading}</h3><p>{children}</p>{action}</div>;}
export function PageHeading({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:ReactNode}){return <header className="page-heading"><div><div className="eyebrow">{eyebrow??'YOUR WORKSPACE'}</div><h1>{title}</h1><p>{description}</p></div>{action}</header>;}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
  const ref=useRef<HTMLDivElement>(null),close=useRef(onClose);close.current=onClose;useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLElement>('input,textarea,select,button')?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.stopPropagation();close.current();}if(event.key==='Tab'){const nodes=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,select,[tabindex="0"]');const first=nodes?.[0],last=nodes?.[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('keydown',key,true);previous?.focus();};},[]);
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><div role="dialog" aria-modal="true" aria-label={title} className={'modal '+(wide?'wide':'')} ref={ref}><div className="modal-title"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={18}/></button></div>{children}</div></div>;
}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint?<small>{hint}</small>:null}</label>;}
export function Toggle({checked,onChange,label,description}:{checked:boolean;onChange:(v:boolean)=>void;label:string;description?:string}){return <label className="toggle-row"><span><strong>{label}</strong>{description?<small>{description}</small>:null}</span><input type="checkbox" className="switch" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>;}
export function AsyncButton({children,action,kind='secondary'}:{children:ReactNode;action:()=>Promise<unknown>;kind?:'primary'|'secondary'|'danger'|'ghost'}){const[busy,setBusy]=useState(false),[error,setError]=useState('');return <><Button kind={kind} disabled={busy} onClick={()=>{setBusy(true);setError('');void action().catch(e=>setError(e instanceof Error?e.message:String(e))).finally(()=>setBusy(false));}}>{busy?<Loader2 size={15} className="spin"/>:null}{children}</Button><ErrorBox message={error}/></>;}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'green'|'orange'}){return <span className={`badge ${tone}`}>{children}</span>;}
export function Saved({show}:{show:boolean}){return show?<span className="saved"><Check size={14}/>Saved locally</span>:null;}
export function ExternalLink({href,children}:{href:string;children:ReactNode}){return <a href={href} target="_blank" rel="noreferrer" className="external-link">{children}<ArrowUpRight size={13}/></a>;}
