import { useEffect, useRef, useState } from 'react';
import { ExternalLink, Monitor, Palette, RotateCcw, Smartphone, X } from 'lucide-react';
import { designEffects, designSchema, designStyles, type DesignSettings, type PreviewAction, type PreviewFrame } from '../shared/design';
import { api, useResource } from './api';
import { AsyncButton, Button, ErrorBox, Field, Toggle } from './components';

export function DesignSidebar({projectId,onClose}:{projectId?:string;onClose:()=>void}){
  const [tab,setTab]=useState<'design'|'preview'>('design');
  return <aside className="design-sidebar" aria-label="Web design studio"><header className="design-heading"><Palette size={17}/><strong>Web design studio</strong><button className="icon-button" aria-label="Close design studio" onClick={onClose}><X size={16}/></button></header><nav className="design-tabs" aria-label="Design studio tabs"><button aria-pressed={tab==='design'} onClick={()=>setTab('design')}><Palette size={14}/>Design</button><button aria-pressed={tab==='preview'} onClick={()=>setTab('preview')}><Monitor size={14}/>Web preview</button></nav>{!projectId?<p className="design-empty">Open a project to save its design choices and preview its website.</p>:<><section hidden={tab!=='design'} className="design-settings"><DesignForm key={projectId} projectId={projectId}/></section>{tab==='preview'?<PreviewViewer key={projectId} projectId={projectId}/>:null}</>}</aside>;
}

function DesignForm({projectId}:{projectId:string}){
  const resource=useResource<DesignSettings>(`/projects/${projectId}/design`,designSchema.parse({}));
  const [draft,setDraft]=useState<DesignSettings|null>(null),[saved,setSaved]=useState(false);
  const value=draft??resource.data;
  const change=(patch:Partial<DesignSettings>)=>{setDraft({...value,...patch});setSaved(false);};
  return <><p className="muted small-text">Choose the look and libraries for this project's next web task. Save the brief, then describe what to build in chat.</p><ErrorBox message={resource.error}/><Toggle label="Use this design brief" checked={value.enabled} onChange={enabled=>change({enabled})} description="Applies to web/UI work in this project."/><div className="section-label">DESIGN STYLE</div><div className="design-styles">{designStyles.map(style=><button key={style.id} aria-pressed={value.style===style.id} onClick={()=>change({style:style.id,enabled:true})}><span className="style-swatches">{style.colors.map(color=><i key={color} style={{background:color}}/>)}</span><strong>{style.name}</strong><small>{style.description}</small></button>)}</div><div className="section-label">OPTIONAL EFFECTS</div><p className="muted small-text">Selected libraries guide generated code; they are installed only in the target project when needed.</p><div className="design-effects">{designEffects.map(effect=><div key={effect.id} className="design-effect"><Toggle label={effect.name} checked={value.effects.includes(effect.id)} description={effect.description} onChange={checked=>change({enabled:true,effects:checked?[...value.effects,effect.id]:value.effects.filter(e=>e!==effect.id)})}/><a href={effect.url} target="_blank" rel="noreferrer">Source · {effect.license}<ExternalLink size={11}/></a>{effect.id==='liquid-logo'?<small className="license-note">PolyForm Shield includes use restrictions. The agent must check the project's use before integration.</small>:null}</div>)}</div><Field label="Design notes" hint="Brand colors, typography, references, or anything to avoid."><textarea rows={3} value={value.notes} onChange={e=>change({notes:e.target.value})} maxLength={2000}/></Field><div className="design-save"><AsyncButton kind="primary" action={async()=>{await api(`/projects/${projectId}/design`,value);await resource.reload();setDraft(null);setSaved(true);}}>Save design brief</AsyncButton><span role="status" className="muted small-text">{saved?'Saved for your next task':draft?'Unsaved changes':''}</span></div></>;
}

function PreviewViewer({projectId}:{projectId:string}){
  const [url,setUrl]=useState('http://localhost:3000'),[width,setWidth]=useState(1280),[active,setActive]=useState(false),[frame,setFrame]=useState<PreviewFrame|null>(null),[error,setError]=useState(''),[text,setText]=useState(''),[busy,setBusy]=useState(false);
  const frameTarget=useRef<HTMLDivElement>(null),alive=useRef(true);
  const endpoint=`/projects/${projectId}/preview`;
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  // Self-scheduling keeps only one screenshot request in flight. Images stay in
  // the UI and never enter the model context or incur provider token usage.
  useEffect(()=>{
    if(!active)return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;
    const poll=async()=>{try{const next=await api<PreviewFrame>(endpoint);if(!cancelled){setFrame(next);setError('');}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:String(e));}finally{if(!cancelled)timer=setTimeout(()=>void poll(),1000);}};
    void poll();return()=>{cancelled=true;clearTimeout(timer);};
  },[active,endpoint]);
  async function act(action:PreviewAction){setBusy(true);setError('');try{await api(endpoint,action);if(alive.current)setActive(true);}catch(e){if(alive.current)setError(e instanceof Error?e.message:String(e));}finally{if(alive.current)setBusy(false);}}
  return <div className="web-preview"><form className="preview-address" onSubmit={e=>{e.preventDefault();void act({action:'navigate',url,width,height:800});}}><input aria-label="Preview URL" type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="http://localhost:3000"/><Button type="submit" disabled={busy}>Open</Button></form><div className="preview-toolbar"><select aria-label="Preview viewport" value={width} onChange={e=>setWidth(Number(e.target.value))}><option value={1280}>Desktop · 1280px</option><option value={768}>Tablet · 768px</option><option value={390}>Mobile · 390px</option></select><Button disabled={!active||busy} onClick={()=>void act({action:'navigate',url:frame?.url??url,width,height:800})}>Apply size</Button><button className="icon-button" aria-label="Refresh preview" disabled={!active||busy} onClick={()=>void act({action:'refresh'})}><RotateCcw size={14}/></button>{frame&&/^https?:/.test(frame.url)?<a className="icon-button" href={frame.url} target="_blank" rel="noreferrer" aria-label="Open preview in browser"><ExternalLink size={14}/></a>:null}</div><ErrorBox message={error}/>{frame?<><div className="preview-caption"><span>{frame.title||'Website preview'}</span><small>{frame.width} × {frame.height}</small></div><div className="preview-canvas" ref={frameTarget} tabIndex={0} role="group" aria-label="Interactive web preview. Click the page, then type or use the text field below." onKeyDown={e=>{
    if(e.key.length===1&&!e.ctrlKey&&!e.metaKey){e.preventDefault();void act({action:'type',text:e.key});}
    else if(['Enter','Tab','Backspace','Delete','Escape','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();void act({action:'key',key:e.key==='Tab'&&e.shiftKey?'Shift+Tab':e.key as Extract<PreviewAction,{action:'key'}>['key']});}
    else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();void act({action:'key',key:'ControlOrMeta+A'});}
  }}><img src={frame.image} alt={`Live preview of ${frame.title||frame.url}`} draggable={false} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();frameTarget.current?.focus();void act({action:'click',x:(e.clientX-r.left)*frame.width/r.width,y:(e.clientY-r.top)*frame.height/r.height});}}/></div><div className="preview-controls"><Button disabled={busy} onClick={()=>void act({action:'scroll',delta:-500})}>Scroll up</Button><Button disabled={busy} onClick={()=>void act({action:'scroll',delta:500})}>Scroll down</Button><Button onClick={()=>setActive(!active)}>{active?'Pause live view':'Resume live view'}</Button></div><form className="preview-type" onSubmit={e=>{e.preventDefault();void act({action:'type',text});setText('');}}><input aria-label="Text for focused preview field" value={text} onChange={e=>setText(e.target.value)} placeholder="Type into the focused page field…"/><Button type="submit" disabled={!text||busy}>Type</Button><Button disabled={busy} onClick={()=>void act({action:'key',key:'Enter'})}>Enter</Button></form>{frame.errors.length?<details className="preview-errors"><summary>{frame.errors.length} browser errors</summary><pre>{frame.errors.join('\n')}</pre></details>:null}<AsyncButton kind="ghost" action={async()=>{setActive(false);await api(endpoint,undefined,'DELETE');setFrame(null);}}>Close browser session</AsyncButton></>:<div className="preview-placeholder"><Smartphone size={30}/><h3>Your website, beside your work.</h3><p>Ask the agent to start the project's dev server, then open its URL here. Local and public sites are supported.</p><p className="small-text">Isolated Chromium · live view · click, type, scroll · no model tokens</p></div>}<p className="muted small-text">Viewport changes take effect with Apply size. Preview uses an isolated browser session; file pickers and popups should be opened in your browser.</p></div>;
}
